# Site settings
title: Wei's Blog
email: wwei2@outlook.com
description: "Simplicity is the ultimate sophistication."
baseurl: ""
url: "http://wwei2.com"
twitter_username: weiweicse
github_username: wweiw

# Build settings
markdown: redcarpet
permalink: pretty
