baseURL = "https://blog.wwei10.com/"
languageCode = "en-us"
title = "Wei Wei"
theme = "minimalist"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "UA-176967303-1"
enableRobotsTXT = true
hasCJKLanguage = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
	author = "Wei Wei"
	description = "Wei's Blog"
	bio = "Engineer at Instagram"

	twitter = ""
	facebook = ""

	enableRSS = true
	RSSLink = "https://feedburner.google.com/fb/a/mailverify?uri=wwei10/blog&amp;loc=en_US"

	enableToc = false

	enableDisqus = false
	disqusShortname = ""

	enableDiscourse = true


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/wwei10"
	twitter-square = "https://www.twitter.com/weiweicse"
	github-square = "https://www.github.com/wwei10"


[markup.goldmark.renderer]
	unsafe= true
